name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'ci.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
  pull_request:
    paths:
      - '**.php'
      - 'ci.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]
        dependencies: [lowest, highest]
        experimental: [false]

    name: PHP ${{ matrix.php }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: cs2pr
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--prefer-dist ${{ matrix.composer-options }}"

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: composer test:unit

      - name: Check .php files for syntax errors
        run: composer test:lint -- --checkstyle | cs2pr

      - uses: actions/cache@v4
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Check composer dependencies for known security issues
        uses: symfonycorp/security-checker-action@v5
        with:
          lock: ./composer.lock
